version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-packing-api:latest
    container_name: nest-packing-api
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-fsS', 'http://127.0.0.1:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
